services:
  fastapi:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:567234@db:5432/hw02
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: db-container
    environment:
      POSTGRES_PASSWORD: 567234
      POSTGRES_USER: postgres
      POSTGRES_DB: hw02
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:
  
networks:
  app-network:
    driver: bridge
